### ISSUE TITLE
[BUG] Support typographic quotes when working with schedules

### ISSUE THREAD

**Issue by zvymazal** [pilosus/dienstplan#119]
**Describe the bug**

The "Use smart quotes and dashes" feature in macOS is an option that automatically converts straight quotation marks (" ") and apostrophes (') into "smart" or typographic quotes. This feature is enabled by default and applies across all applications.

Unfortunately the code doesn't recognise these quotes as valid and complains with the following error:
```
Usage:
@dienstplan schedule <subcommand> "<executable>" <crontab>
...
Caveats:
"<executable>" must be enclosed in the double quotation marks
```

**To Reproduce**
1. Any schedule operation that requires <executable> to be enclosed in double quotation marks results in this error.

**Expected behavior**
Recognise and accept typographic quotes as valid.

**Workaround**
Disable "Use smart quotes and dashes" feature in `Keyboard` -> `Text Input` settings.

**Screenshots**
<img width="565" alt="Screenshot 2024-09-23 at 09 15 26" src="https://github.com/user-attachments/assets/e0537947-638e-4cd1-aeb3-6bab9b70d7a8">

**Application setup*
 - Docker image: [pilosus/dienstplan:1.1.109](https://hub.docker.com/layers/pilosus/dienstplan/1.1.109/images/sha256-d145142a3c81de8449fe40b69c23395cee20ac13229922f6c4ec9a54ca1c4993?context=explore)

**Comment by pilosus** [comment]
Thanks for reporting!

I think the best approach would be to sanitize user input by substituting typographic quotes to plain vanilla double quotes before using the regular expression [here](https://github.com/pilosus/dienstplan/blob/110fe000b59fa1e01d4601e6617cdfa2e790397c/src/dienstplan/commands.clj#L399) as there possibly are more than one way smart quotes work depending on the language/keyboard layout.

**Comment by pilosus** [comment]
I need to check how the smart quotes feature works on MacOS, because there are quite a few options for quotation marks in different languages, see [summary](https://en.m.wikipedia.org/wiki/Quotation_mark) here. If MacOS supports them all, then modifying the regex would probably make it too cumbersome.

**Comment by zvymazal** [comment]
Fair enough 😅 I don't know anything about Clojure but let me know if I can help in any way.

**Comment by pilosus** [comment]
I think this is the most extensible and readable way to tackle the problem:

1. Let's sanitize the arguments like this:

```diff
--- a/src/dienstplan/commands.clj
+++ b/src/dienstplan/commands.clj
@@ -396,7 +396,8 @@ Caveats:
 (defn parse-args-schedule-cmd
   [command-parsed]
   (let [args (get-command-args command-parsed)
-        matcher (re-matcher regex-schedule args)
+        args' (string/replace args #"[“”«»„‟‹›❝❞]" "\"")
+        matcher (re-matcher regex-schedule args')
         result (when (.matches matcher)
                  {:subcommand (.group matcher "subcommand")
                   :executable (.group matcher "executable")
```

2. And extend tests [here](https://github.com/pilosus/dienstplan/blob/main/test/dienstplan/commands_test.clj#L121).
3. (optionally) test with the real Slack requests

I'm happy to accept a pull request for this.

**Comment by pilosus** [comment]
@zvymazal released:
https://github.com/pilosus/dienstplan/releases/tag/1.1.112
