### ISSUE TITLE
Add assign command

### ISSUE THREAD

**Issue by BurlakovNick** [pilosus/dienstplan#36]
Sometimes it's handy to assign specific person to skip someone in the rotation (e.g. they're sick or on vacation). It can be done with several `rotate` commands, but it's not convenient.

Command could look like this
```
dienstplan assign <rota> user
```

**Comment by pilosus** [comment]
Sounds good. The command's convention is also in line with what's been done so far:
```
@dienstplan assign <rota-name> <user-mention>
```

The expected behav is the following. Let's say we've got a rota called `duty` with user list `@user1 @user2 @user3 @user4`. If the current oncall person is `@user1` and we tell to the bot `@dienstplan assign duty @user3`, then `@user3` becomes a current on-call and the order of users remains as it was.

Feel free to submit a PR.

**Comment by BurlakovNick** [comment]
> Feel free to submit a PR.
I'll try, feel free to assign "assign" issue on me :)

**Comment by pilosus** [comment]
Done
