### ISSUE TITLE
[FEATURE] mention on-duty person without duty description

### ISSUE THREAD

**Issue by PoisonousJohn** [pilosus/dienstplan#57]
**Is your feature request related to a problem? Please describe.**
Sometimes we need to mention an on-duty person as a reaction to some event as we normally do by mentioning some slack group.

For example: "@duty-group could you please take a look"

**Describe the solution you'd like**
Could we please support something like `@dienstplan attention rotation_name` so the bot will mention the on-duty person?

**Comment by pilosus** [comment]
Let's call a new command `shout`.
This is how it's going to work like:

<img width="638" alt="dienstplan-shout-command" src="https://user-images.githubusercontent.com/6400248/169647187-8db9b0b9-d3dd-435f-85ff-bdb552024287.png">
